#!/bin/bash
### BEGIN INIT INFO
# Provides: sinusbot
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start sinusbot
# Description: Start sinusbot
### END INIT INFO
 
SINUS_PATH="/opt/sinusbot/"
SINUS_FILE="sinusbot"
SINUS_USER="teamspeak"
SCREEN_NAME="sinusbot"
 
start_ts() {
	echo "Lancement du BOT"
        chown -R $SINUS_USER:$SINUS_USER $SINUS_PATH && chmod 775 -R $SINUS_PATH
	su $SINUS_USER -c "screen -dmS $SCREEN_NAME $SINUS_PATH./$SINUS_FILE"
}
 
stop_ts() {
	echo "Arrêt du BOT"
	su $SINUS_USER -c "screen -X -S $SCREEN_NAME quit"
        chown -R $SINUS_USER:$SINUS_USER $SINUS_PATH && chmod 775 -R $SINUS_PATH
}
 
case "$1" in
	start)
		start_ts
		;;
	stop)
		stop_ts
		;;
	restart)
		stop_ts
		sleep 2
		start_ts
		;;
	*)
		echo "Usage du script : $0 {start|stop|restart}"
		;;
esac